### ISSUE TITLE
What licence is this code offered under?

### ISSUE THREAD

**Issue by LukePrior** [chrisys/mini-lora-weatherstation#6]
Hi,

I was just wondering what software licence this code is offered under as I was considering creating a localised guide for my region.

Cheers

**Comment by LukePrior** [comment]
Here is a guide on how to set licence type: https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/adding-a-license-to-a-repository

MIT would be great.

**Comment by chrisys** [comment]
@Uskompuf MIT licence added; thanks for the prompt. I encourage you to contribute back to this repo so we can keep all developments in one place, but no pressure - have fun and build stuff 👍
